version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # RabbitMQ management plugin
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mysql_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
        - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql
  postgres-user:
    image: postgres:latest
    container_name: postgres-user
    environment:
        POSTGRES_DB: postgre_db_user
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    volumes:
        - postgres_user:/var/lib/postgresql/data
  postgres-todo:
    image: postgres:latest
    container_name: postgres-todo
    environment:
        POSTGRES_DB: postgre_db_todo
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports:
        - "5431:5432"
    volumes:
        - postgres_todo:/var/lib/postgresql/data


volumes:
  rabbitmq_data:
  mysql_data:
  postgres_user:
  postgres_todo: