name: Create Release

on:
  push:
    branches: main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"
          always-auth: "true"
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: pnpm install --frozen-lockfile
        env:
         NODE_AUTH_TOKEN: ${{secrets.TOKEN_GTH}}
      - run: |
          pnpm release --ci
        env:
         GITHUB_TOKEN: ${{secrets.TOKEN_GTH}}
